server:
  port: 8000
spring:
  profiles:
    active: dev
    include:
    - feign
  application:
    name: service-order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}
logging:
  level:
    com.knowwen.feign: debug
    
---
spring:
  config:
    import:
    - nacos:db.yml
    - nacos:common.yml
    - nacos:db-order.yml
    activate:
      on-profile:
      - dev
---
spring:
  config:
    import:
    - nacos:db.yml
    - nacos:common.yml
    - nacos:test.yml
    activate:
      on-profile:
      - test
---
spring:
  config:
    import:
    - nacos:db.yml
    - nacos:common.yml
    activate:
      on-profile:
      - prod