
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: service-oauth2
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
      authorizationserver:
        client:
          gateway:
            registration:
              client-id: "gateway"
              client-secret: "$2a$10$0r0iJ8KXXKLU69fJxpNXf.vT.gwNJmlTXQQgn5fqCogmsq58M4eke"
              client-authentication-methods:
                - "client_secret_post"
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1/login/oauth2/code/gateway"
#                - "http://localhost:5173/"
              post-logout-redirect-uris:
                - "http://127.0.0.1/"
              scopes:
                - "openid"
                - "profile"
                - "user"
            require-authorization-consent: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active}
      discovery:
        namespace: ${spring.profiles.active}

---
spring:
  config:
    import:
      # - nacos:db.yml
      - nacos:service-oauth2-db.yml
    activate:
      on-profile:
        - dev
---
spring:
  config:
    import:
      - nacos:db.yml
    activate:
      on-profile:
        - test
---
spring:
  config:
    import:
      - nacos:db.yml
    activate:
      on-profile:
        - prod